# Generated by Django 3.0.3 on 2020-02-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('grade_year', models.TextField(blank=True, null=True)),
                ('number_of_student', models.IntegerField(blank=True, null=True)),
                ('average', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=25, unique=True)),
                ('student_name', models.CharField(max_length=25)),
                ('student_surname', models.CharField(max_length=25)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Grade')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=10)),
                ('final_mark', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Grade')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('id_number', models.CharField(blank=True, max_length=25, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=25, unique=True)),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
                ('town', models.CharField(blank=True, max_length=25, null=True)),
                ('province', models.CharField(blank=True, max_length=25, null=True)),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.StudentDetails')),
            ],
            options={
                'db_table': 'student_address',
            },
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('parent_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('cell', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('occupation', models.CharField(blank=True, max_length=25, null=True)),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.StudentDetails')),
            ],
            options={
                'db_table': 'parent_details',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_type', models.CharField(blank=True, max_length=4, null=True)),
                ('mark_name', models.CharField(max_length=10)),
                ('mark', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
            options={
                'db_table': 'mark',
            },
        ),
    ]
