# Generated by Django 3.0.3 on 2020-02-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='number_of_student',
            new_name='number_of_students',
        ),
    ]
