# Generated by Django 3.0.3 on 2020-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200222_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_year',
            field=models.CharField(default='2020', max_length=4),
        ),
    ]
