# Generated by Django 3.0.3 on 2020-03-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200315_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
    ]
