# Generated by Django 3.0.4 on 2020-03-29 20:38

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200315_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='term',
        ),
        migrations.AddField(
            model_name='grade',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.CharField(choices=[(management.models.Terms['T1'], 'TERM1'), (management.models.Terms['T2'], 'TERM2'), (management.models.Terms['T3'], 'TERM3'), (management.models.Terms['T4'], 'TERM4')], default='TERM1', max_length=5),
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
