# Generated by Django 3.0.4 on 2020-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200329_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='grade_id',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
