# Generated by Django 3.0.4 on 2020-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200411_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prev_grade_id',
            field=models.IntegerField(default=0),
        ),
    ]
