# Generated by Django 3.0.4 on 2020-04-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200419_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='final_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
