# Generated by Django 3.0.4 on 2020-04-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_subject_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
