# Generated by Django 3.0.4 on 2020-04-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_subject_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
    ]
