# Generated by Django 3.0.4 on 2020-04-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Grade'),
            preserve_default=False,
        ),
    ]
