# Generated by Django 3.0.4 on 2020-04-26 23:21

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('grade_year', models.CharField(default='2020', max_length=4)),
                ('number_of_students', models.IntegerField(blank=True, null=True)),
                ('average', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=25, unique=True)),
                ('student_name', models.CharField(max_length=25)),
                ('student_surname', models.CharField(max_length=25)),
                ('prev_grade_id', models.IntegerField(default=0)),
                ('grade_name', models.CharField(default='', max_length=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Grade')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=10)),
                ('students', django_mysql.models.ListCharField(models.IntegerField(), default=[], max_length=110, size=6)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Grade')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('id_number', models.CharField(blank=True, max_length=25, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=25, unique=True)),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
                ('town', models.CharField(blank=True, max_length=25, null=True)),
                ('province', models.CharField(blank=True, max_length=25, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
            options={
                'db_table': 'student_address',
            },
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('parent_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('cell', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('occupation', models.CharField(blank=True, max_length=25, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
            options={
                'db_table': 'parent_details',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_type', models.CharField(blank=True, max_length=4, null=True)),
                ('mark_name', models.CharField(max_length=10)),
                ('mark', models.DecimalField(decimal_places=0, max_digits=10)),
                ('term', models.CharField(choices=[(management.models.Terms['T1'], 'TERM1'), (management.models.Terms['T2'], 'TERM2'), (management.models.Terms['T3'], 'TERM3'), (management.models.Terms['T4'], 'TERM4')], default='TERM1', max_length=5)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
            options={
                'db_table': 'mark',
            },
        ),
    ]
