# Generated by Django 3.0.4 on 2020-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.AddField(
            model_name='subject',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
