# Generated by Django 3.0.4 on 2020-05-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200503_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrolment',
            fields=[
                ('enrolment_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
            ],
            options={
                'db_table': 'subject_enrolment',
            },
        ),
    ]
