# Generated by Django 3.0.4 on 2020-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200503_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='prev_grade_id',
            field=models.IntegerField(default=0),
        ),
    ]
